cask_args appdir: "/Applications"

# Taps

tap "adoptopenjdk/openjdk"
tap "dart-lang/dart"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "mongodb/brew"
tap "rigellute/tap"
tap "zegervdv/zathura"

# Binaries

brew "python@3.9"
brew "glib"
brew "gdk-pixbuf"
brew "gobject-introspection"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "adwaita-icon-theme"
brew "node", link: false
brew "anime-downloader"
brew "webp"
brew "aom"
brew "python@3.10"
brew "asciinema"
brew "atk"
brew "automake"
brew "bash"
brew "bat"
brew "bats"
brew "cc65"
brew "gcc"
brew "tbb"
brew "cmake"
brew "coreutils"
brew "exercism"
brew "fd"
brew "libtool"
brew "guile"
brew "gnutls"
brew "little-cms2"
brew "tesseract"
brew "ffmpeg"
brew "open-mpi"
brew "fzf"
brew "git-lfs"
brew "glslviewer"
brew "gnu-prolog"
brew "gnupg"
brew "go"
brew "gradle"
brew "gsettings-desktop-schemas"
brew "gtk+3"
brew "hdf5"
brew "lua"
brew "highlight"
brew "httpie"
brew "libheif"
brew "python@3.8"
brew "imagemagick"
brew "io"
brew "jasper"
brew "jenv"
brew "leiningen"
brew "libgsf"
brew "libmatio"
brew "libproxy"
brew "libxml2"
brew "luarocks"
brew "lynx"
brew "mas"
brew "ninja"
brew "meson"
brew "mono", link: false
brew "n"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "nghttp2"
brew "nnn"
brew "numpy", link: false
brew "pyqt@5"
brew "vtk"
brew "opencv"
brew "openjdk@11"
brew "pacvim"
brew "pandoc"
brew "tree"
brew "pass"
brew "qt"
brew "poppler"
brew "postgresql"
brew "pyqt"
brew "python@2", link: false
brew "qemu"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "rlwrap"
brew "ruby"
brew "sbt"
brew "scala"
brew "sip"
brew "sphinx-doc"
brew "tmux"
brew "vim"
brew "vips"
brew "wifi-password"
brew "yarn"
brew "youtube-dl"
brew "zlib"
brew "zsh-autosuggestions"
brew "dart-lang/dart/dart"
brew "heroku/brew/heroku", link: false
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "mongodb/brew/mongodb-community"
brew "rigellute/tap/spotify-tui"
brew "zegervdv/zathura/girara", args: ["HEAD"]
brew "zegervdv/zathura/zathura", args: ["HEAD"]
brew "zegervdv/zathura/zathura-pdf-poppler"

# Apps

cask "1password"
cask "adoptopenjdk8"
cask "alacritty"
cask "appcleaner"
cask "balenaetcher"
cask "bettertouchtool"
cask "betterzip"
cask "caffeine"
cask "cheatsheet"
cask "dash"
cask "discord"
cask "firefox"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "java11"
cask "keepassxc"
cask "keybase"
cask "keycastr"
cask "mactex-no-gui"
cask "ngrok"
cask "nordvpn"
cask "notion"
cask "obsidian"
cask "paparazzi"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "raycast"
cask "slack"
cask "spotify"
cask "suspicious-package"
cask "webpquicklook"

# Mac App Store

mas "Craft", id: 1487937127
mas "Flow", id: 1423210932
mas "GoodNotes", id: 1444383602
mas "KakaoTalk", id: 869223134
mas "Magnet", id: 441258766
