cask_args appdir: "/Applications"

# Taps
tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

# Mac App Store
brew "mas"

mas "Magnet", id: 441258766
mas "Xcode", id: 497799835

# Apps
cask "adobe-creative-cloud"
cask "adoptopenjdk8"
cask "alfred"
cask "appcleaner"
cask "dash"
cask "figma"
cask "firefox"
cask "font-hack-nerd-font"
cask "iterm2"
cask "java11"
cask "mactex-no-gui"
cask "ngrok"
cask "nordvpn"
cask "slack"
cask "visual-studio-code"
cask "zoomus"

# Apps/Quicklook
cask "betterzip"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "suspicious-package"
cask "webpquicklook"

# Binaries
brew "automake"
brew "bat"
brew "openssl@1.1"
brew "cmake"
brew "coreutils"
brew "curl"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "git-lfs"
brew "glslviewer"
brew "gradle"
brew "grep"
brew "eslint"
brew "icu4c"
brew "imagemagick"
brew "jenv"
brew "libtool"
brew "icu4c"
brew "luarocks"
brew "mono"
brew "neovim", args: ["HEAD"]
brew "nnn"
brew "node"
brew "openjdk@11"
brew "openssl@1.1"
brew "pandoc"
brew "ruby-build"
brew "rbenv"
brew "rlwrap"
brew "ruby"
brew "tmux"
brew "tree"
brew "vim"
brew "vips"
brew "wifi-password"
brew "yarn"
brew "youtube-dl"
brew "zlib"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
