require("core/options")
require("core/keymapping")
require("core/plugins")
require("core/colorscheme")

require("config/barbar")
require("config/coc")
require("config/dashboard")
require("config/galaxyline")
require("config/neorg")
require("config/nvim-tree")
require("config/telescope")
require("config/todo-comments")
require("config/treesitter")
require("config/vimwiki")
