require("core/options")
require("core/keymapping")
require("core/plugins")
require("core/colorscheme")

require("config/startify")
require("config/barbar")
require("config/coc")
require("config/todo-comments")
require("config/chadtree")
require("config/telescope")
require("config/vimwiki")
require("config/autopairs")
