" Generated by vim-plug
" Tue Sep  5 17:23:30 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['coc.nvim'].commit = 'b8bf528af61cf1c036d971480b5feced21be662b'
silent! let g:plugs['context.vim'].commit = '108644e146c864995288dee7dacf219267917ac1'
silent! let g:plugs['fzf'].commit = '0f50dc848e58b47408713c2c31f2be73287c030a'
silent! let g:plugs['fzf.vim'].commit = '1be10b0e50a9b2053293444f0ddc1da5629fe6fd'
silent! let g:plugs['goyo.vim'].commit = 'fa0263d456dd43f5926484d1c4c7022dfcb21ba9'
silent! let g:plugs['lightline.vim'].commit = 'f11645cc6d37871244f2ea0ae972d3f6af9c8f73'
silent! let g:plugs['markdown-preview.nvim'].commit = '02cc3874738bc0f86e4b91f09b8a0ac88aef8e96'
silent! let g:plugs['nerdtree'].commit = '32168889bdbc1e7d1d313e3e41c1cc794b38eac5'
silent! let g:plugs['onedark.vim'].commit = '57b77747694ea5676c3ca0eeaf9567dc499730c0'
silent! let g:plugs['vim-commentary'].commit = 'e87cd90dc09c2a203e13af9704bd0ef79303d755'
silent! let g:plugs['vim-css-color'].commit = '6cc65734bc7105d9677ca54e2255fcbc953ba6bf'
silent! let g:plugs['vim-devicons'].commit = '71f239af28b7214eebb60d4ea5bd040291fb7e33'
silent! let g:plugs['vim-fugitive'].commit = '572c8510123cbde02e8a1dafcd376c98e1e13f43'
silent! let g:plugs['vim-nerdtree-syntax-highlight'].commit = '35e70334a2ff6e89b82a145d1ac889e82d1ddb4e'
silent! let g:plugs['vim-polyglot'].commit = 'bc8a81d3592dab86334f27d1d43c080ebf680d42'
silent! let g:plugs['vim-startify'].commit = '81e36c352a8deea54df5ec1e2f4348685569bed2'

PlugUpdate!

