- name: Set up macOS dev environment
  hosts: local

  vars_files:
    - config.yaml

  roles:
    - name: fonts
      tags: fonts

    - name: dotfiles
      tags: dotfiles

    - name: zsh
      tags: zsh

    - name: nvim
      tags: nvim

    - name: node
      tags: node

    - name: go
      tags: go

    - name: docker
      tags: docker

    - name: tmux
      tags: tmux

    - name: system_defaults
      tags: system_defaults
