-- local Plugin = { "nvim-neorg/neorg" }
--
-- Plugin.version = "*"
--
-- Plugin.dependencies = {
--   "luarocks.nvim",
-- }
--
-- Plugin.lazy = false
--
-- Plugin.ft = { "norg" }
--
-- Plugin.opts = {
--   load = {
--     ["core.defaults"] = {},
--     ["core.completion"] = { -- A wrapper to interface with several different completion engines.
--       config = {
--         engine = "nvim-cmp",
--       },
--     },
--     ["core.concealer"] = {}, --  Enhances the basic Neorg experience by using icons instead of text.
--     ["core.dirman"] = { --  Responsible for managing Neorg directories.
--       config = {
--         workspaces = {
--           home = "~/pkm/neorg",
--         },
--         default_workspace = "home",
--         index = "index.norg", -- The name of the root .norg file
--       },
--     },
--     ["core.export"] = {}, --  Exports Neorg documents into any other supported filetype.
--     ["core.export.markdown"] = {}, --  Interface for `core.export` to allow exporting to Markdown.
--     ["core.presenter"] = { -- Creates presentation slides.
--       config = {
--         zen_mode = "zen-mode",
--       },
--     },
--     ["core.summary"] = {}, -- Creates links to all files in any workspace.
--     ["core.ui.calendar"] = {}, -- Opens an interactive calendar for date-related tasks.
--   },
-- }
--
-- return Plugin

return {}
