return {
  "nvim-treesitter/nvim-treesitter",

  branch = "master",

  build = ":TSUpdate",

  main = "nvim-treesitter.configs", -- Sets main module to use for opts

  opts = {
    folds = { enable = true },
    highlight = { enable = true },
    indent = { enable = true },
    sync_install = false,
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "cpp",
      "css",
      "diff",
      "dockerfile",
      "glsl",
      "go",
      "graphql",
      "html",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "python",
      "regex",
      "rust",
      "scss",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "vue",
      "yaml",
    },
  },
}
